services:
  team-api:
    container_name: fastapi-server
    image: ${BACKEND_IMAGE:-backend-team-api}
    env_file: .env
    ports:
      - 8000:8000
    restart: unless-stopped

  team-nginx:
    container_name: nginx-server
    image: nginx:1.27-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - team-api
    restart: unless-stopped
