"""add_seoul_sales

Revision ID: 53f7328270a5
Revises: b49186160704
Create Date: 2026-06-22 01:28:12.676628

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53f7328270a5'
down_revision: Union[str, Sequence[str], None] = 'b49186160704'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'seoul_sales',
        sa.Column('quarter_code', sa.String(length=10), nullable=False),
        sa.Column('dong_code', sa.String(length=15), nullable=False),
        sa.Column('service_code', sa.String(length=20), nullable=False),
        sa.Column('dong_name', sa.Text(), nullable=True),
        sa.Column('service_name', sa.Text(), nullable=True),
        sa.Column('monthly_sales_amt', sa.BigInteger(), nullable=True),
        sa.Column('monthly_sales_cnt', sa.Integer(), nullable=True),
        sa.Column('weekday_sales_amt', sa.BigInteger(), nullable=True),
        sa.Column('weekend_sales_amt', sa.BigInteger(), nullable=True),
        sa.Column('mon_sales_amt', sa.BigInteger(), nullable=True),
        sa.Column('tue_sales_amt', sa.BigInteger(), nullable=True),
        sa.Column('wed_sales_amt', sa.BigInteger(), nullable=True),
        sa.Column('thu_sales_amt', sa.BigInteger(), nullable=True),
        sa.Column('fri_sales_amt', sa.BigInteger(), nullable=True),
        sa.Column('sat_sales_amt', sa.BigInteger(), nullable=True),
        sa.Column('sun_sales_amt', sa.BigInteger(), nullable=True),
        sa.Column('hour_00_06_sales_amt', sa.BigInteger(), nullable=True),
        sa.Column('hour_06_11_sales_amt', sa.BigInteger(), nullable=True),
        sa.Column('hour_11_14_sales_amt', sa.BigInteger(), nullable=True),
        sa.Column('hour_14_17_sales_amt', sa.BigInteger(), nullable=True),
        sa.Column('hour_17_21_sales_amt', sa.BigInteger(), nullable=True),
        sa.Column('hour_21_24_sales_amt', sa.BigInteger(), nullable=True),
        sa.Column('male_sales_amt', sa.BigInteger(), nullable=True),
        sa.Column('female_sales_amt', sa.BigInteger(), nullable=True),
        sa.Column('age_10_sales_amt', sa.BigInteger(), nullable=True),
        sa.Column('age_20_sales_amt', sa.BigInteger(), nullable=True),
        sa.Column('age_30_sales_amt', sa.BigInteger(), nullable=True),
        sa.Column('age_40_sales_amt', sa.BigInteger(), nullable=True),
        sa.Column('age_50_sales_amt', sa.BigInteger(), nullable=True),
        sa.Column('age_60_plus_sales_amt', sa.BigInteger(), nullable=True),
        sa.Column('weekday_sales_cnt', sa.Integer(), nullable=True),
        sa.Column('weekend_sales_cnt', sa.Integer(), nullable=True),
        sa.Column('mon_sales_cnt', sa.Integer(), nullable=True),
        sa.Column('tue_sales_cnt', sa.Integer(), nullable=True),
        sa.Column('wed_sales_cnt', sa.Integer(), nullable=True),
        sa.Column('thu_sales_cnt', sa.Integer(), nullable=True),
        sa.Column('fri_sales_cnt', sa.Integer(), nullable=True),
        sa.Column('sat_sales_cnt', sa.Integer(), nullable=True),
        sa.Column('sun_sales_cnt', sa.Integer(), nullable=True),
        sa.Column('hour_00_06_sales_cnt', sa.Integer(), nullable=True),
        sa.Column('hour_06_11_sales_cnt', sa.Integer(), nullable=True),
        sa.Column('hour_11_14_sales_cnt', sa.Integer(), nullable=True),
        sa.Column('hour_14_17_sales_cnt', sa.Integer(), nullable=True),
        sa.Column('hour_17_21_sales_cnt', sa.Integer(), nullable=True),
        sa.Column('hour_21_24_sales_cnt', sa.Integer(), nullable=True),
        sa.Column('male_sales_cnt', sa.Integer(), nullable=True),
        sa.Column('female_sales_cnt', sa.Integer(), nullable=True),
        sa.Column('age_10_sales_cnt', sa.Integer(), nullable=True),
        sa.Column('age_20_sales_cnt', sa.Integer(), nullable=True),
        sa.Column('age_30_sales_cnt', sa.Integer(), nullable=True),
        sa.Column('age_40_sales_cnt', sa.Integer(), nullable=True),
        sa.Column('age_50_sales_cnt', sa.Integer(), nullable=True),
        sa.Column('age_60_plus_sales_cnt', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('quarter_code', 'dong_code', 'service_code'),
    )
    op.create_index(
        'ix_seoul_sales_dong_code', 'seoul_sales', ['dong_code'], unique=False
    )
    op.create_index(
        'ix_seoul_sales_quarter', 'seoul_sales', ['quarter_code'], unique=False
    )
    op.create_index(
        'ix_seoul_sales_service_code', 'seoul_sales', ['service_code'], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_seoul_sales_service_code', table_name='seoul_sales')
    op.drop_index('ix_seoul_sales_quarter', table_name='seoul_sales')
    op.drop_index('ix_seoul_sales_dong_code', table_name='seoul_sales')
    op.drop_table('seoul_sales')
    # ### end Alembic commands ###
