"""add geo_store table

Revision ID: b49186160704
Revises: 
Create Date: 2026-06-21 13:33:42.535052

"""
from typing import Sequence, Union

import geoalchemy2
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b49186160704'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('geo_store',
    sa.Column('id', sa.String(length=30), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('branch', sa.Text(), nullable=True),
    sa.Column('category_large_code', sa.String(length=10), nullable=True),
    sa.Column('category_large_name', sa.Text(), nullable=True),
    sa.Column('category_mid_code', sa.String(length=10), nullable=True),
    sa.Column('category_mid_name', sa.Text(), nullable=True),
    sa.Column('category_small_code', sa.String(length=10), nullable=True),
    sa.Column('category_small_name', sa.Text(), nullable=True),
    sa.Column('gu_code', sa.String(length=10), nullable=True),
    sa.Column('gu_name', sa.Text(), nullable=True),
    sa.Column('dong_code', sa.String(length=15), nullable=True),
    sa.Column('dong_name', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('postal_code', sa.String(length=10), nullable=True),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_geo_store_category_small', 'geo_store', ['category_small_code'], unique=False)
    op.create_index('ix_geo_store_dong_code', 'geo_store', ['dong_code'], unique=False)
    op.create_index('ix_geo_store_location', 'geo_store', ['location'], unique=False, postgresql_using='gist')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_geo_store_location', table_name='geo_store', postgresql_using='gist')
    op.drop_index('ix_geo_store_dong_code', table_name='geo_store')
    op.drop_index('ix_geo_store_category_small', table_name='geo_store')
    op.drop_table('geo_store')
    # ### end Alembic commands ###
