"""add_local_people

Revision ID: f9eda7c46578
Revises: 53f7328270a5
Create Date: 2026-06-22 02:00:21.875658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9eda7c46578'
down_revision: Union[str, Sequence[str], None] = '53f7328270a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('local_people',
    sa.Column('date_id', sa.String(length=8), nullable=False),
    sa.Column('time_slot', sa.String(length=2), nullable=False),
    sa.Column('dong_code', sa.String(length=15), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('male_0_9', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('male_10_14', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('male_15_19', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('male_20_24', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('male_25_29', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('male_30_34', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('male_35_39', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('male_40_44', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('male_45_49', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('male_50_54', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('male_55_59', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('male_60_64', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('male_65_69', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('male_70_plus', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('female_0_9', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('female_10_14', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('female_15_19', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('female_20_24', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('female_25_29', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('female_30_34', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('female_35_39', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('female_40_44', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('female_45_49', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('female_50_54', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('female_55_59', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('female_60_64', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('female_65_69', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('female_70_plus', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.PrimaryKeyConstraint('date_id', 'time_slot', 'dong_code')
    )
    op.create_index('ix_local_people_dong_code', 'local_people', ['dong_code'], unique=False)
    op.create_index('ix_local_people_time_slot', 'local_people', ['time_slot'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_local_people_time_slot', table_name='local_people')
    op.drop_index('ix_local_people_dong_code', table_name='local_people')
    op.drop_table('local_people')
    # ### end Alembic commands ###
